### ISSUE TITLE
Use specific naming rather than generic. 

### ISSUE THREAD

**Issue by MehediMayall** [habiburrahman-mu/Buy-and-Rent-Home-WebAPI#4]
src/Core/Application/Interfaces
src/Core/Domain/Interfaces

These interfaces are playing an important role here. They are aiding in communication with external services. In my opinion, it should be renamed Contracts. It expresses responsibilities. Otherwise, the interface name does not express any responsibility except for what they are.

**Comment by habib-july** [comment]
Thanks for raising this interesting point about renaming our interfaces to contracts. I understand your perspective that "Contracts" might better express the responsibilities these interfaces define.

While there's merit to that idea, here are some reasons why I'm hesitant to make the switch:
- **Clarity:** "Interfaces" is a familiar term in programming, promoting clear code understanding. "Contracts" might be less familiar and require explanation.
- **Accuracy:** "Interfaces" are technical, focusing on method signatures and functionalities. "Contracts" have broader connotations that might not apply here.
- **Maintainability:** Renaming all interfaces would be a lot of work while refactoring. 

What do you think about these considerations? I'm open to further discussion and finding a solution that works well.

**Comment by habiburrahman-mu** [comment]
Thanks for raising this interesting point about renaming our interfaces to contracts. I understand your perspective that "Contracts" might better express the responsibilities these interfaces define.

While there's merit to that idea, here are some reasons why I'm hesitant to make the switch:
- **Clarity:** "Interfaces" is a familiar term in programming, promoting clear code understanding. "Contracts" might be less familiar and require explanation.
- **Accuracy:** "Interfaces" are technical, focusing on method signatures and functionalities. "Contracts" have broader connotations that might not apply here.
- **Maintainability:** Renaming all interfaces would be a lot of work while refactoring. 

What do you think about these considerations? I'm open to further discussion and finding a solution that works well.

**Comment by MehediMayall** [comment]
When you have multiple classes that have relationships between them, group them based on their behavior. Behavior is a better option than technical grouping of classes in resolving the complexity of class relationships.
